// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://egynzlsptbolyiukqbhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneW56bHNwdGJvbHlpdWtxYmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mzg4MzksImV4cCI6MjA2NzMxNDgzOX0.IdKAZFHLmq2EaXLZRN4SdvXFiyY5mPMZwGX2PIkCFNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);